[workspace]
members=[
    "app",
    "c_from_rust",
    "complex",
    "dining_philosophers",
    "imgtool",
    "into_map_demo",
    "logic_gates",
    "macro_map",
    "rust_from_c",
    "super_player",
    "user_auth",
    "xtnet"
]

